INSERT INTO PERMISSION
VALUES ('Green', 'Green');

INSERT INTO PERMISSION
VALUES ('Gold', 'Gold');

INSERT INTO PERMISSION
VALUES ('Gold', 'Green');

INSERT INTO PERMISSION
VALUES ('Evening Orange', 'Gold');

INSERT INTO PERMISSION
VALUES ('Evening Orange', 'Green');

INSERT INTO PERMISSION
VALUES ('Evening Orange', 'Orange');

INSERT INTO PERMISSION
VALUES ('Orange', 'Orange');

INSERT INTO PERMISSION
VALUES ('Orange', 'Gold');

INSERT INTO PERMISSION
VALUES ('Orange', 'Green');

INSERT INTO PERMISSION
VALUES ('Purple', 'Purple');

INSERT INTO PERMISSION
VALUES ('Purple', 'Orange');

INSERT INTO PERMISSION
VALUES ('Purple', 'Gold');

INSERT INTO PERMISSION
VALUES ('Purple', 'Green');

INSERT INTO PERMISSION
VALUES ('Accessible', 'Accessible');

INSERT INTO USER 
VALUES ('2020000000', 'iluvdbs', 'Ayo', 'Adereti', 'ara19001@utdallas.edu', '8328478041');

INSERT INTO USER 
VALUES ('4020000000', 'bamzy2dworld', 'Bamzy', 'America', 'ara19001@utdallas.edu', '8328478041');

SELECT *
FROM USER;

INSERT INTO PERMIT 
VALUES ('OMGPermit1','2020000000', 'Green');

INSERT INTO PERMIT 
VALUES ('TestPermit','4020000000', 'Purple');

SELECT *
FROM PERMIT;


INSERT INTO PLATE_NUM
VALUES ('OMGPermit1', 'WOW123');

SELECT *
FROM PLATE_NUM;

INSERT INTO PARKING_LOT
VALUES ('Lot A', 156);

SELECT *
FROM PARKING_LOT;

INSERT INTO PARKING_SPOT
VALUES ('Lot A', 45, 'Green');

INSERT INTO PARKING_SPOT
VALUES ('Lot A', 4, 'Orange');

SELECT *
FROM PARKING_SPOT;

INSERT INTO RESERVES (Rstart, Rend, Utd_id, Lot_name, Spot_num)
VALUES ('2024-04-04 08:00:00', '2024-04-04 10:30:00', '2020000000', 'Lot A', 45);

SELECT * 
FROM RESERVES;
